### ISSUE TITLE
Rejected Credit card has status of "Pending" in Woocommerce Subscriptions

### ISSUE THREAD

**Issue by GregorioCorrea** [mobbexco/woocommerce-subscriptions#15]
La tarjeta de crédito rechazada tiene el estado 'Pendiente' en las suscripciones de Woocommerce.
Una vez que se accede a https://mobbex.com/p/subscriptions/B4RNP0IEIJXQCM9DDZ/subscriber/QN79N28H86CT4RF4PZ/source/
Si la tarjeta no pudo ser validada, devuelve a Woocomerce Subscriptions el estado Pendiente de pago para el pedido, lo que genera que no pueda volver a intentarse el pago si el cliente sale de la página de checkout.

Les comparto capturas de pantalla que muestran el caso. Abrir en orden descendiente, fueron tomadas en secuencia, entre las pantallas en incógnito del cliente de testing (usuario1.testingclubdelhabito@gmail.com) y el administrador de WordPress en https://testing.clubdelhabito.com/wp-admin/

![image](https://user-images.githubusercontent.com/110120893/181373934-3bf26232-0573-4628-8615-e8966889c097.png)
![image](https://user-images.githubusercontent.com/110120893/181374188-9b5c99af-34fd-43bc-bdf5-800de0303bf9.png)
![image](https://user-images.githubusercontent.com/110120893/181374847-47dd9ebf-0be0-451d-83f2-7cd30e04f802.png)
![image](https://user-images.githubusercontent.com/110120893/181375039-84b0dfcd-7af1-4e0e-96af-ee61cbdad8a4.png)
![image](https://user-images.githubusercontent.com/110120893/181375082-475ba2b7-a45a-4ee0-9058-b2d72b7d5515.png)
![image](https://user-images.githubusercontent.com/110120893/181375129-08ab43dd-d639-4a38-9bb9-ac9ee28bda54.png)
![image](https://user-images.githubusercontent.com/110120893/181375158-918556f9-b52c-40e6-a360-8acb62fcb4a7.png)
![image](https://user-images.githubusercontent.com/110120893/181375188-bf3f7d1f-01ac-4a7b-8a55-147d2a92bdf6.png)
![image](https://user-images.githubusercontent.com/110120893/181375226-7e2f80db-8342-4f39-b47b-4fb071e3dda2.png)

**Comment by jlmobbex** [comment]
Hola @GregorioCorrea! Gracias por tus comentarios, actualmente estamos revisando el inconveniente. Nos comunicaremos del lado del soporte para pedirte algunos datos de la instalación.

**Comment by jlmobbex** [comment]
#17
