### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function get_id() luego de actualizar a WooCommerce Subscriptions v4.7.0

### ISSUE THREAD

**Issue by leandroprz** [mobbexco/woocommerce-subscriptions#23]
Actualicé a la versión 4.7.0 de WooCommerce Subscriptions y comencé a ver este error relacionado al plugin de Mobbex:

`Fatal error: Uncaught Error: Call to a member function get_id() on bool in D:\wamp64\www\newsite\wp-content\plugins\woocommerce-subscriptions\vendor\woocommerce\subscriptions-core\includes\wcs-order-functions.php:360 Stack trace: #0 D:\wamp64\www\newsite\wp-content\plugins\woocommerce-mobbex-subs\includes\cart.php(105): wcs_order_contains_subscription(false) #1 D:\wamp64\www\newsite\wp-includes\class-wp-hook.php(308): Mbbxs_Cart::filter_checkout_payment_gateways(Array) #2 D:\wamp64\www\newsite\wp-includes\plugin.php(205): WP_Hook->apply_filters(Array, Array) #3 D:\wamp64\www\newsite\wp-content\plugins\woocommerce\includes\class-wc-payment-gateways.php(163): apply_filters('woocommerce_ava...', Array) #4 D:\wamp64\www\newsite\wp-content\plugins\woocommerce-paypal-payments\modules\ppcp-button\src\Assets\SmartButton.php(464): WC_Payment_Gateways->get_available_payment_gateways() #5 D:\wamp64\www\newsite\wp-content\plugins\woocommerce-paypal-payments\modules\ppcp-button\src\Assets\SmartButton.php(238): WooCommerce\PayPalCommer in D:\wamp64\www\newsite\wp-content\plugins\woocommerce-subscriptions\vendor\woocommerce\subscriptions-core\includes\wcs-order-functions.php on line 360

Ha habido un error crítico en esta web.

[Aprende más sobre el diagnóstico de WordPress.](https://wordpress.org/support/article/faq-troubleshooting/)`

Si desactivo el plugin de Mobbex el error desaparece. Desactivando el plugin de PayPal el error sigue apareciendo.

Edit: haciendo downgrade a la versión 4.6.0 de WooCommerce Subscriptions el error no aparece.

**Comment by leandroprz** [comment]
La versión 4.8.0 de WooCommerce Subscriptions corrige este problema.

**Comment by leandroprz** [comment]
Reabro este ticket porque el error sigue apareciendo al intentar ver un pedido:

```
Detalles del error
==================
Se ha producido un error del tipo E_ERROR en la línea 122 del archivo /home/******/public_html/wp-content/plugins/woocommerce-mobbex-subs/includes/helper.php. Mensaje de error: Uncaught Error: Call to a member function get_id() on bool in /home/******/public_html/wp-content/plugins/woocommerce-mobbex-subs/includes/helper.php:122
Stack trace:
#0 /home/******/public_html/wp-content/plugins/woocommerce-mobbex-subs/includes/helper.php(106): Mbbxs_Helper->has_subscription(5758)
#1 /home/******/public_html/wp-content/plugins/woocommerce-mobbex-subs/includes/admin/order-settings.php(38): Mbbxs_Helper->has_any_subscription(5758)
#2 /home/******/public_html/wp-includes/class-wp-hook.php(310): Mbbx_Subs_Order_Settings::add_subscription_panel('shop_order')
#3 /home/******/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#4 /home/******/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /home/******/public_html/wp-admin/includes/meta-boxes.php(1599): do_action('add_meta_boxes', 'shop_order', Object(WP_Post))
#6 /home/******/public_html/wp-admin/edit-form-advanced.php(271): register_and_do_post_meta_boxes(Object(WP_Post))
#7 /
```

WordPress versión 6.1.1
Tema activo: Fluxus Child Theme (versión 1.6.1)
Plugin actual: Mobbex Subscriptions for WooCommerce (versión 2.2.0)
PHP versión 7.4.33

**Comment by jlmobbex** [comment]
Hola @leandroprz! Gracias por tus comentarios, te comento que este error ya está corregido y publicado en la última versión de nuestro plugin ([v2.3.0](https://github.com/mobbexco/woocommerce-subscriptions/releases/tag/2.3.0)).
