### ISSUE TITLE
Ha habido un error critico en esta web

### ISSUE THREAD

**Issue by gonbanchero** [mobbexco/woocommerce-subscriptions#28]
Hola, como están?

Con la versión 2.2.0 instalada y activando el plugin WooCommerce PayPal Payments se rompe el sitio y aparece pantalla de error. 
Estaba funcionando todo ok, hasta que tuve que instalar el plugin de paypal y sucedio lo que comento. 
Probé desactivando plugin por plugin hasta dar con el de ustedes. Hice downgrade a la versión 2.1.2 y el error desaparece. 
Podran revisarlo?

<img width="1440" alt="Captura_de_Pantalla_2023-01-05_a_las_14 22 04" src="https://user-images.githubusercontent.com/85972008/210844762-1d3050ae-5230-417b-b033-d6daa428e777.png">

Gracias!

**Comment by jlmobbex** [comment]
Buen día @gonbanchero! Te pido que actualices a la última versión del plugin para comprobar si este error queda resuelto o aún persiste. Dejo el link de la release: https://github.com/mobbexco/woocommerce-subscriptions/releases/tag/2.3.0

**Comment by jlmobbex** [comment]
Buenas tardes @gonbanchero! Cierro esta issue por inactividad. Si el error persiste te pido que abras otra y agregues una referencia a esta misma.
