### ISSUE TITLE
Problemas con las version 2.2.0

### ISSUE THREAD

**Issue by ignacio-linares** [mobbexco/woocommerce-subscriptions#29]
Hola! Tengo la versión 2.2.0 de Mobbex Subscriptions for WooCommerce, la versión 7.4.1 de Woocommerce, la versión 6.1.1 de Wordpress y la versión 4.7.0 de WooCommerce Subscriptions. El sitio se rompe al activar Mobbex Subscriptions para woocommerce. Me da el siguiente error:

` Fatal error: Uncaught Error: Call to a member function get_id() on bool
in /home/u350622584/domains/pethome.com.ar/public_html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/wcs-order-functions.php on line 352

Call stack:

wcs_order_contains_subscription()
wp-content/plugins/woocommerce-mobbex-subs/includes/cart.php:105
Mbbxs_Cart::filter_checkout_payment_gateways()
wp-includes/class-wp-hook.php:308
WP_Hook::apply_filters()
wp-includes/plugin.php:205
apply_filters()
wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php:163
WC_Payment_Gateways::get_available_payment_gateways()
wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/gateways/class-wc-subscriptions-core-payment-gateways.php:158
WC_Subscriptions_Core_Payment_Gateways::one_gateway_supports()
wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-cart-validator.php:37
WC_Subscriptions_Cart_Validator::maybe_empty_cart()
wp-includes/class-wp-hook.php:308
WP_Hook::apply_filters()
wp-includes/plugin.php:205
apply_filters()
wp-content/plugins/woocommerce/includes/class-wc-form-handler.php:822
WC_Form_Handler::add_to_cart_handler_simple()
wp-content/plugins/woocommerce/includes/class-wc-form-handler.php:796
WC_Form_Handler::add_to_cart_action()
wp-includes/class-wp-hook.php:308
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:332
WP_Hook::do_action()
wp-includes/plugin.php:517
do_action()
wp-settings.php:639
require_once()
wp-config.php:84
require_once()
wp-load.php:50
require_once()
wp-blog-header.php:13
require()
index.php:17
Query Monitor` 

Y no logró poder activar mobbex subscription para mi ecommerce, como podría hacer?

**Comment by jlmobbex** [comment]
Hola @ignacio-linares! Te comento que investigamos y corregimos este bug en la última versión del plugin ([v2.3.0](https://github.com/mobbexco/woocommerce-subscriptions/releases/tag/2.3.0)) que quedó publicada en estos días. Muchas gracias por tus comentarios!
