### ISSUE TITLE
Se produjo un error al procesar la transacción. Intente nuevamente

### ISSUE THREAD

**Issue by rosariokhouri** [mobbexco/woocommerce-subscriptions#42]
Hola! No consigo integrar el plugin. He seguido los pasos de la documentación pero no me permite avanzar en el checkout. Cuando elijo pagar, me muestra el error Se produjo un error al procesar la transacción. Intente nuevamente.

**Comment by jlmobbex** [comment]
Hola @rosariokhouri! Te pido que te comuniques con el soporte de Mobbex desde ayuda@mobbex.com, ya que es muy probable que este error tenga origen en la configuración de la entidad.
