### ISSUE TITLE
Errores en Version 3.0.1

### ISSUE THREAD

**Issue by erpwoosync** [mobbexco/woocommerce-subscriptions#44]
Mi web dejó de funcionar con la ultima versión y el log de Apache nos muestra errores de tablas inexistentes en el momento de finalizar la compra en el checkout

[Tue Sep 12 13:21:20.914367 2023] [proxy_fcgi:error] [pid 7600:tid 139731727775488] [client 138.97.239.19:42192] AH01071: Got error 'PHP message: PHP Notice: Undefined index: mailjet_woo_subscribe_ok in /home/erpwoosy/public_html/wp-content/plugins/mailjet-for-wordpress/src/includes/SettingsPages/WooCommerceSettings.php on line 158PHP message: order was called incorrectly. Subscription properties should not be accessed directly as WooCommerce 3.0 no longer supports direct property access. Use WC_Subscription::get_parent() instead. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_Mbbx_Subs->process_payment, WC_Gateway_Mbbx_Subs->get_subscription, Mbbxs_Helper->get_post_id, WC_Subscription->__get, wcs_doing_it_wrong, wc_doing_it_wrong. This message was added in version 2.2.0.PHP message: WordPress database error Table 'erpwoosy_wp829.wp_mobbex_subscription' doesn't exist for query SELECT * FROM wp_mobbex_subscription WHERE product_id='8714' made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_Mbbx_Subs->process_payment, WC_Gateway_Mbbx_Subs->get_subscription, Mbbxs_Helper->get_post_id, MobbexSubscription::is_storedPHP message: WordPress database error Table 'erpwoosy_wp829.wp_mobbex_subscription' doesn't exist for query SELECT * FROM wp_mobbex_subscription WHERE product_id=6074 LIMIT 1; made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_Mbbx_Subs->process_payment, WC_Gateway_Mbbx_Subs->get_subscription, Mbbxs_Helper->create_mobbex_subscription, MobbexSubscription->__construct, Mobbex\\Model->__construct, Mobbex\\Model->load, Mobbex\\Model->get_dataPHP message: WordPress database error Table 'erpwoosy_wp829.wp_mobbex_subscription' doesn't exist for query SHOW FULL COLUMNS FROM `wp_mobbex_subscription` made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_Mbbx_Subs->process_payment, WC_Gateway_Mbbx_Subs->get_subscription, Mbbxs_Helper->create_mobbex_subscription, MobbexSubscription->save, Mobbex\\Model->savePHP message: WordPress database error Table 'erpwoosy_wp829.wp_mobbex_subscriber' doesn't exist for query SELECT * FROM wp_mobbex_subscriber WHERE order_id=8714 LIMIT 1; made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_Mbbx_Subs->process_payment, WC_Gateway_Mbbx_Subs->get_subscriber, MobbexSubscriber->__construct, Mobbex\\Model->__construct, Mobbex\\Model->load, Mobbex\\Model->get_dataPHP message: WordPress database error Table 'erpwoosy_wp829.wp_mobbex_subscription' doesn't exist for query SELECT * FROM wp_mobbex_subscription WHERE uid='ITEOQ2RQD0LCC1GDCH' made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_Mbbx_Subs->process_payment, WC_Gateway_Mbbx_Subs->get_subscriber, MobbexSubscriber->save, MobbexSubscriber->sync, MobbexSubscription::get_by_uidPHP message: PHP Fatal error: Uncaught Error: Call to a member function calculateDates() on null in /home/erpwoosy/public_html/wp-content/plugins/woocommerce-subscriptions-master/includes/class-subscriber.php:79Stack trace:#0 /home/erpwoosy/public_html/wp-content/plugins/woocommerce-subscriptions-master/includes/class-subscriber.php(187): MobbexSubscriber->sync()#1 /home/erpwoosy/public_html/wp-content/plugins/woocommerce-subscriptions-master/includes/gateway.php(487): MobbexSubscriber->save()#2 /home/erpwoosy/public_html/wp-content/plugins/woocommerce-subscriptions-master/includes/gateway.php(209): WC_Gateway_Mbbx_Subs->get_subscriber()#3 /home/erpwoosy/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1050): WC_Gateway_Mbbx_Subs->process_payment()#4 /home/erpwoosy/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1279): WC_Checkout->process_order_payment()#5 /home/erpwoosy/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.ph...', referer: https://www.erpwoosync.com/checkout/

**Comment by jlmobbex** [comment]
Hola @erpwoosync! El error muestra que no se pudieron instalar las actualizaciones en la base de datos, y esto probablemente se deba a que la instalación se realizó utilizando el código de master (esto se ve en el nombre directorio del plugin que quedó como `woocommerce-subscriptions-master`). Para descargar la última versión del plugin hay que dirijirse a la pestaña de releases del repositorio, y desde ahí hacer click en `wcs-mobbex.x.y.z.zip`.

**Comment by jlmobbex** [comment]
Cierro la issue ya que se comentó que el problema quedó resuelto en la issue mencionada.
