### ISSUE TITLE
cambio de estado pedido

### ISSUE THREAD

**Issue by PabloGonzalez315** [mobbexco/woocommerce-subscriptions#48]
Hola, buenas tardes, para comentarles que con la ultima actualización los pedidos recurrentes no están cambiando de estado a pesar de que el proceso de compra finaliza.
así mismo con el Query monitor me arroja un error en el cual dice que no existe la tabla wp-mobbex-logs por ende no puedo ver los registros en la sección que ubicaron allí.

el tema es con las suscripciones porque el plugin de compra "principal" de producto funciona correctamente.

el sitio funciona con localización dinamica segun el pais de origen cambia la moneda a dolar o peso argentino, 
funcionaba correctamente ahora en la parte de nota del pedido en los pedidos de woocommerce figura "Error durante el cambio de estado. PayPal order ID not found in meta." Siendo que paypal no estaría activo para el pagos en pesos.

**Comment by erpwoosync** [comment]
Nosotros tampoco podemos hacer andar esta última versión, no se puede hacer nuevos pedidos ni tampoco se renuevan las suscripciones existentes que tenemos hace 2 años ya funcionando con WooCommerce Subscriptions y Mobbex.

Volví a la versión 2.3.0 en la cual se renuevan las suscripciones, pero los pedidos quedan en estado de pendiente de pago y luego se pasan a cancelados por falta de pago… desde el soporte por mail no obtengo una solución definitiva.

**Comment by erpwoosync** [comment]
@jlmobbex alguna novedad?

**Comment by jlmobbex** [comment]
Hola @PabloGonzalez315! Gracias por tus comentarios, ya tenemos visto el problema y estamos preparando la publicación donde queda corregido. @erpwoosync creo que son problemas distintos por como afectan al funcionamineto, este lo seguimos viendo en #44.

**Comment by jlmobbex** [comment]
Buenas tardes @PabloGonzalez315! Ya está disponible la nueva versión con cambios relacionados a la actualización de estados, te pido si podés volver a intentar el pago con esta versión instalada. Recordá descargar el archivo con formato `wcs-mobbex.x.y.z.zip` desde la pestaña de releases del repositorio.

**Comment by PabloGonzalez315** [comment]
Hola @jlmobbex ya acabo de subir el nuevo, en primera instancia hizo el cobro bien e hizo el cambio de estado a completado, esperemos mañana la renovación del pedido, estoy en contacto con lucia vía mail de igual forma

**Comment by erpwoosync** [comment]
@jlmobbex Nosotros también subimos la nueva versión y probamos una renovación de suscripción y funciono correctamente.

**Comment by jlmobbex** [comment]
Buenísimo! Muchas gracias sus comentarios, cierro la issue ya que quedó resuelto el problema.
